version: "3.7"
services:
  webapp:
    build: .
    ports:
      - "8080:8080"

# ENVIRONMENT VARIABLE EXAMPLE
#version: "3.7"
#services:
#  webapp:
#    build: .
#    ports:
#      - "8080:8080"
#    environment:
#      - training_name=123
#      - training_step=3


# VOLUME MOUNTING EXAMPLE
#version: "3.7"
#services:
#  webapp:
#    build: .
#    ports:
#      - "8080:8080"
#    environment:
#      - training_name=123
#      - training_step=3
#    volumes:
#      - type: bind
#        source: ./application.properties
#        target: /config/application.properties