apiVersion: v1
kind: Service
metadata:
  name: java-fake-service
  namespace: default
  labels:
    app_name: java-fake-service
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app_name: java-fake-service
